---
  - name: installing {{ web_pkg }} package
    yum:
      name: "{{ web_pkg }}"
      state: present

  - name: start and enable {{ web_svc }} service
    service:
      name: "{{ web_svc }}"
      state: started
      enabled: true

  - name: opening {{ web_rule }} service in the firewall
    firewalld:
      service: "{{ web_rule }}"
      state: enabled
      permanent: true
      immediate: true

  - name: copy hello.txt file to managed node
    copy:
      src: hello.txt
      dest: /home/admin/hello.txt

  - name: copying index.html.j2 file
    template:
      src: index.html.j2
      dest: /var/www/html/index.html
    notify:
      - restart httpd service

