---
  - name: installing {{ db_pkg }} package
    yum:
      name: "{{ db_pkg }}"
      state: present

  - name: startng and enabling {{ db_svc }} service
    service:
      name: "{{ db_svc }}"
      state: started
      enabled: true

  - name: opening {{ db_rule }} service in the firewall
    firewalld:
      service: "{{ db_rule }}"
      state: enabled
      permanent: true
      immediate: true
